### ISSUE TITLE
Still a scrolling issue on market page/ via iOS

### ISSUE THREAD

**Issue by Eskyee** [tokenocean/raretoshi#16]
Leaving this here as a reminder @asoltys for raretoshi 

While scrolling raretoshi on a iPhone.. Market page still jumps and is jittery, but all other pagers seem fine via IOS but not tested on a android device.

**Comment by secondl1ght** [comment]
Update: this will be refactored and fixed soon.

**Comment by Eskyee** [comment]
Cheers 🍻

**Comment by Eskyee** [comment]
I Can confirm latest fix is working fine on iOS & laptop 

Excellent xx Thanks to the team xx 

https://github.com/tokenocean/raretoshi/commit/1ffa4503597fed66e8e76dd6775a906702a5f21f
