### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by asoltys** [tokenocean/raretoshi#18]
Getting a bunch of warnings during front-end production build, would be nice to address these:

9:35:26 PM [vite-plugin-svelte] /app/src/routes/a/[slug].svelte:418:12 A11y: <a> element should have an href attribute
416:           </div>
417:           <div class="w-full mb-2">
418:             <a
                 ^
419:               on:click={handleDelete}
420:               class="block text-center text-sm secondary-btn w-full cursor-pointer"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:66:14 A11y: Screenreaders already announce <img> elements as an image.
64:                 > and navigate to “Sign in” at the top right corner.
65:               </p>
66:               <img
                  ^
67:                 class="guide-image"
68:                 src="/guide/image19.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:74:14 A11y: Screenreaders already announce <img> elements as an image.
72:             <li>
73:               <p>Select "Don’t have an account? Sign up."</p>
74:               <img
                  ^
75:                 class="guide-image"
76:                 src="/guide/image35.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:85:14 A11y: Screenreaders already announce <img> elements as an image.
83:                 password.
84:               </p>
85:               <img
                  ^
86:                 class="guide-image"
87:                 src="/guide/image23.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:96:14 A11y: Screenreaders already announce <img> elements as an image.
94:                 instructions provided to validate your email address.
95:               </p>
96:               <img
                  ^
97:                 class="guide-image"
98:                 src="/guide/image2.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:101:14 A11y: Screenreaders already announce <img> elements as an image.
 99:                 alt="guide-image"
100:               />
101:               <img
                   ^
102:                 class="guide-image"
103:                 src="/guide/image22.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:135:14 A11y: Screenreaders already announce <img> elements as an image.
133:                 NFTs will be lost forever.
134:               </p>
135:               <img
                   ^
136:                 class="guide-image"
137:                 src="/guide/image16.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:140:14 A11y: Screenreaders already announce <img> elements as an image.
138:                 alt="guide-image"
139:               />
140:               <img
                   ^
141:                 class="guide-image"
142:                 src="/guide/image33.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:145:14 A11y: Screenreaders already announce <img> elements as an image.
143:                 alt="guide-image"
144:               />
145:               <img
                   ^
146:                 class="guide-image"
147:                 src="/guide/image7.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:157:14 A11y: Screenreaders already announce <img> elements as an image.
155:                 you are done click "Next."
156:               </p>
157:               <img
                   ^
158:                 class="guide-image"
159:                 src="/guide/image25.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:165:14 A11y: Screenreaders already announce <img> elements as an image.
163:             <li>
164:               <p>Your wallet is now ready to be funded.</p>
165:               <img
                   ^
166:                 class="guide-image"
167:                 src="/guide/image34.png"
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:234:10 A11y: Screenreaders already announce <img> elements as an image.
232:             a confidential address and corresponding QR code.
233:           </p>
234:           <img class="guide-image" src="/guide/image17.png" alt="guide-image" />
               ^
235:           <p>
236:             It can take 3-6 min for the funds to show up in your wallet. If you
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:265:10 A11y: Screenreaders already announce <img> elements as an image.
263:             not in a rush.
264:           </p>
265:           <img class="guide-image" src="/guide/image6.png" alt="guide-image" />
               ^
266:         </div>
267:         <div class="item" id="btc-lightning">
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:279:10 A11y: Screenreaders already announce <img> elements as an image.
277:             maximum of 0.01 BTC with this funding option.
278:           </p>
279:           <img class="guide-image" src="/guide/image30.png" alt="guide-image" />
               ^
280:         </div>
281:         <div class="item" id="upload-artwork-and-mint-nft">
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:296:10 A11y: Screenreaders already announce <img> elements as an image.
294:             formats are jpg, png, gif and mp4 up to a size limit of 400MB.
295:           </p>
296:           <img class="guide-image" src="/guide/image11.png" alt="guide-image" />
               ^
297:           <img class="guide-image" src="/guide/image4.png" alt="guide-image" />
298:           <p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:297:10 A11y: Screenreaders already announce <img> elements as an image.
295:           </p>
296:           <img class="guide-image" src="/guide/image11.png" alt="guide-image" />
297:           <img class="guide-image" src="/guide/image4.png" alt="guide-image" />
               ^
298:           <p>
299:             You will be presented with a “Submit artwork” form. You can either
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:304:10 A11y: Screenreaders already announce <img> elements as an image.
302:             once your artwork is ready
303:           </p>
304:           <img class="guide-image" src="/guide/image3.png" alt="guide-image" />
               ^
305:           <img class="guide-image" src="/guide/image1.png" alt="guide-image" />
306:           <p>You can now fill out details of your artwork including:</p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:305:10 A11y: Screenreaders already announce <img> elements as an image.
303:           </p>
304:           <img class="guide-image" src="/guide/image3.png" alt="guide-image" />
305:           <img class="guide-image" src="/guide/image1.png" alt="guide-image" />
               ^
306:           <p>You can now fill out details of your artwork including:</p>
307:           <ul style="list-style: disc; padding-left: 30px">
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:337:10 A11y: Screenreaders already announce <img> elements as an image.
335:             </li>
336:           </ul>
337:           <img class="guide-image" src="/guide/image21.png" alt="guide-image" />
               ^
338:           <p>
339:             After clicking “Submit” your artwork will be uploaded into our IPFS
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:352:10 A11y: Screenreaders already announce <img> elements as an image.
350:             history of the artwork on the bottom left corner).
351:           </p>
352:           <img class="guide-image" src="/guide/image37.png" alt="guide-image" />
               ^
353:           <p>
354:             Once the minting transaction is confirmed, your artwork/NFT will be
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:360:10 A11y: Screenreaders already announce <img> elements as an image.
358:             until listed.
359:           </p>
360:           <img class="guide-image" src="/guide/image5.png" alt="guide-image" />
               ^
361:           <p>
362:             The NFT will also be in your wallet now. You can confirm this by
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:367:10 A11y: Screenreaders already announce <img> elements as an image.
365:             your wallet including L-BTC and NFTs.
366:           </p>
367:           <img class="guide-image" src="/guide/image10.png" alt="guide-image" />
               ^
368:           <img class="guide-image" src="/guide/image28.png" alt="guide-image" />
369:         </div>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:368:10 A11y: Screenreaders already announce <img> elements as an image.
366:           </p>
367:           <img class="guide-image" src="/guide/image10.png" alt="guide-image" />
368:           <img class="guide-image" src="/guide/image28.png" alt="guide-image" />
               ^
369:         </div>
370:         <div class="item" id="list-artwork">
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:380:10 A11y: Screenreaders already announce <img> elements as an image.
378:             uploaded artwork under the “Creations” tab.
379:           </p>
380:           <img class="guide-image" src="/guide/image8.png" alt="guide-image" />
               ^
381:           <img class="guide-image" src="/guide/image24.png" alt="guide-image" />
382:           <p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:381:10 A11y: Screenreaders already announce <img> elements as an image.
379:           </p>
380:           <img class="guide-image" src="/guide/image8.png" alt="guide-image" />
381:           <img class="guide-image" src="/guide/image24.png" alt="guide-image" />
               ^
382:           <p>
383:             2. Select the unlisted piece that you want to publicly list by
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:387:10 A11y: Screenreaders already announce <img> elements as an image.
385:             be able to list it by clicking on “List.”
386:           </p>
387:           <img class="guide-image" src="/guide/image14.png" alt="guide-image" />
               ^
388:           <img class="guide-image" src="/guide/image26.png" alt="guide-image" />
389:           <p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:388:10 A11y: Screenreaders already announce <img> elements as an image.
386:           </p>
387:           <img class="guide-image" src="/guide/image14.png" alt="guide-image" />
388:           <img class="guide-image" src="/guide/image26.png" alt="guide-image" />
               ^
389:           <p>
390:             3. You will now be presented with several options for your listing
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:426:10 A11y: Screenreaders already announce <img> elements as an image.
424:             history of the artwork if you scroll down.
425:           </p>
426:           <img class="guide-image" src="/guide/image9.png" alt="guide-image" />
               ^
427:           <img class="guide-image" src="/guide/image13.png" alt="guide-image" />
428:           <img class="guide-image" src="/guide/image12.png" alt="guide-image" />
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:427:10 A11y: Screenreaders already announce <img> elements as an image.
425:           </p>
426:           <img class="guide-image" src="/guide/image9.png" alt="guide-image" />
427:           <img class="guide-image" src="/guide/image13.png" alt="guide-image" />
               ^
428:           <img class="guide-image" src="/guide/image12.png" alt="guide-image" />
429:           <p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:428:10 A11y: Screenreaders already announce <img> elements as an image.
426:           <img class="guide-image" src="/guide/image9.png" alt="guide-image" />
427:           <img class="guide-image" src="/guide/image13.png" alt="guide-image" />
428:           <img class="guide-image" src="/guide/image12.png" alt="guide-image" />
               ^
429:           <p>
430:             Other users will now be able to make you an offer or directly buy
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:433:10 A11y: Screenreaders already announce <img> elements as an image.
431:             your artwork if a price was set.
432:           </p>
433:           <img class="guide-image" src="/guide/image38.png" alt="guide-image" />
               ^
434:         </div>
435:         <div class="item" id="auction">
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:444:10 A11y: Screenreaders already announce <img> elements as an image.
442:             you’ll accept for the artwork. Setting one is optional.
443:           </p>
444:           <img class="guide-image" src="/guide/image27.png" alt="guide-image" />
               ^
445: 
446:           <p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:458:10 A11y: Screenreaders already announce <img> elements as an image.
456:             and how much time is left until the auction ends.
457:           </p>
458:           <img class="guide-image" src="/guide/image36.png" alt="guide-image" />
               ^
459:         </div>
460:         <div class="item" id="what-to-expect-after-listing">
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:481:10 A11y: Screenreaders already announce <img> elements as an image.
479:             NFT and it will reflect the new owner.
480:           </p>
481:           <img class="guide-image" src="/guide/image31.png" alt="guide-image" />
               ^
482:           <img class="guide-image" src="/guide/image20.png" alt="guide-image" />
483:           <img class="guide-image" src="/guide/image32.png" alt="guide-image" />
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:482:10 A11y: Screenreaders already announce <img> elements as an image.
480:           </p>
481:           <img class="guide-image" src="/guide/image31.png" alt="guide-image" />
482:           <img class="guide-image" src="/guide/image20.png" alt="guide-image" />
               ^
483:           <img class="guide-image" src="/guide/image32.png" alt="guide-image" />
484:           <p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:483:10 A11y: Screenreaders already announce <img> elements as an image.
481:           <img class="guide-image" src="/guide/image31.png" alt="guide-image" />
482:           <img class="guide-image" src="/guide/image20.png" alt="guide-image" />
483:           <img class="guide-image" src="/guide/image32.png" alt="guide-image" />
               ^
484:           <p>
485:             If you decide to list your artwork as an auction, Raretoshi users
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:503:10 A11y: Screenreaders already announce <img> elements as an image.
501:           <h4>7.1 Edit your Raretoshi profile</h4>
502:           <p>1. Go to your profile page</p>
503:           <img class="guide-image" src="/guide/image11.png" alt="guide-image" />
               ^
504: 
505:           <p>2. Select "Edit Profile"</p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:506:10 A11y: Screenreaders already announce <img> elements as an image.
504: 
505:           <p>2. Select "Edit Profile"</p>
506:           <img class="guide-image" src="/guide/image15.png" alt="guide-image" />
               ^
507: 
508:           <p>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/guide/index.svelte:512:10 A11y: Screenreaders already announce <img> elements as an image.
510:             and save the changes. Done.
511:           </p>
512:           <img class="guide-image" src="/guide/image18.png" alt="guide-image" />
               ^
513:         </div>
514:       </div>
9:35:27 PM [vite-plugin-svelte] /app/src/routes/help/index.svelte:141:2 Unused CSS selector ".contact h5"
139:     border-radius: 10px;
140:   }
141:   .contact h5 {
       ^
142:     margin-bottom: 10px;
143:   }
9:35:28 PM [vite-plugin-svelte] /app/src/routes/a/_form.svelte:121:2 Unused CSS selector ".tooltip"
119: 
120: <style>
121:   .tooltip {
       ^
122:     cursor: pointer;
123:   }
9:35:28 PM [vite-plugin-svelte] /app/src/routes/a/_form.svelte:124:2 Unused CSS selector ".tooltip .tooltip-text"
122:     cursor: pointer;
123:   }
124:   .tooltip .tooltip-text {
       ^
125:     display: none;
126:     padding: 15px;
9:35:28 PM [vite-plugin-svelte] /app/src/routes/a/_form.svelte:132:2 Unused CSS selector ".tooltip:hover .tooltip-text"
130:     font-style: normal;
131:   }
132:   .tooltip:hover .tooltip-text {
       ^
133:     display: block;
134:   }
9:35:29 PM [vite-plugin-svelte] /app/src/components/ArtworkMedia.svelte:144:4 A11y: <img> element should have an alt attribute
142:     class="p-5 bg-primary/50 flex justify-center items-center h-full w-full mx-auto rounded-lg"
143:   >
144:     <img src class="hidden" bind:this={aud} />
         ^
145:     <figure>
146:       <Fa icon={faHeadphones} class="mx-auto" size="3x" />
9:35:29 PM [vite-plugin-svelte] /app/src/components/ArtworkMedia.svelte:147:6 A11y: <figcaption> must be first or last child of <figure>
145:     <figure>
146:       <Fa icon={faHeadphones} class="mx-auto" size="3x" />
147:       <figcaption class="text-center">NFT audio file</figcaption>
           ^
148: 
149:       {#if noAudio === false}
"differenceInMilliseconds" is imported from external module "date-fns" but never used in "src/routes/auth/refresh.json.js", "src/routes/auth/login.js", "src/hooks/index.js", "src/routes/a/_comments.svelte", "src/lib/countdown.js", "src/routes/galleries/index.svelte", "src/lib/utils.js", "src/lib/wallet.js", "src/components/Activity.svelte", "src/components/Offers.svelte", "src/components/TransactionTime.svelte", "src/routes/a/[slug]/auction.svelte", "src/routes/a/[slug].svelte", "src/routes/market/_sort.svelte", "src/routes/market/index.svelte" and "src/routes/wallet/_transactions.svelte".
"v4" is imported from external module "uuid" but never used in "src/routes/artworks/[slug].json.js", "src/routes/a/create.svelte" and "src/routes/a/[slug]/transfer.svelte".
✓ 235 modules transformed.
Generated an empty chunk: "entries/endpoints/transfer"
Generated an empty chunk: "entries/endpoints/wallet/balances.json"
rendering chunks...

**Comment by ahopk127** [comment]
I've addressed most of the warnings in https://github.com/tokenocean/raretoshi/commit/73bd4906535b424efcb34865f57d2a7d002561d7.  For your information, most of the warnings were one of these two things:
- Images not having proper alt text
- Unused CSS selectors

There were a few minor errors I've left open:
- Some imported packages have errors, and dealing with them is not our responsibility
- I left some unused JS imports in case we need to use them again

![Screenshot 2022-05-24 170459](https://user-images.githubusercontent.com/73263261/170133878-237d8053-8ce0-4466-9358-84f4e7201b68.png)
